name = "ConvexPolygons"
uuid = "bd678e46-537b-4837-9db2-8bbb0917495c"
authors = ["Paulo Jabardo <pjabardo@ipt.br>"]
version = "0.1.0"

[deps]
CircularArrays = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
